# MegaLinter Configuration for Voice Communicator
# Documentation: https://megalinter.io/configuration/

# Apply fixes
APPLY_FIXES: all
APPLY_FIXES_EVENT: commit
APPLY_FIXES_MODE: commit

# Show elapsed time for performance monitoring
SHOW_ELAPSED_TIME: true

# Flavor optimized for JavaScript/TypeScript projects
FLAVOR_SUGGESTIONS: false

# Enable specific linters for our tech stack
ENABLE:
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - JSON_JSONLINT
  - JSON_PRETTIER
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - DOCKERFILE_HADOLINT
  - HTML_HTMLHINT
  - CSS_STYLELINT
  - SCSS_STYLELINT
  - SPELL_CSPELL

# Disable problematic linters that might conflict with our setup
DISABLE:
  - COPYPASTE_JSCPD  # Can be too strict for small projects
  - REPOSITORY_SECRETLINT  # May flag false positives
  - REPOSITORY_GITLEAKS  # May flag false positives

# File patterns to exclude from linting
FILTER_REGEX_EXCLUDE: |
  (node_modules/|dist/|build/|coverage/|\.git/|\.vscode/|\.idea/|report/)

# TypeScript specific configuration
TYPESCRIPT_ES_FILTER_REGEX_INCLUDE: "(src/.*\\.ts$)"
TYPESCRIPT_ES_CONFIG_FILE: ".eslintrc.js"

# Prettier configuration
PRETTIER_FILTER_REGEX_INCLUDE: "(src/.*\\.(ts|js|json|md|yml|yaml|html|css|scss)$)"

# JSON linting
JSON_JSONLINT_FILTER_REGEX_INCLUDE: "(package\\.json|tsconfig\\.json|manifest\\.json|\\.eslintrc\\.json)$"

# Markdown configuration
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdownlint.json"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(node_modules/|CHANGELOG\\.md)"

# HTML configuration
HTML_HTMLHINT_CONFIG_FILE: ".htmlhintrc"

# CSS/SCSS configuration
CSS_STYLELINT_CONFIG_FILE: ".stylelintrc.json"
SCSS_STYLELINT_CONFIG_FILE: ".stylelintrc.json"

# Spell checking
SPELL_CSPELL_CONFIG_FILE: "cspell.json"

# Reporting
REPORTERS:
  - consoleReporter
  - textReporter
  - githubStatusReporter

# Output configuration
LOG_LEVEL: INFO
PRINT_ALPACA: false
PRINT_ALL_FILES: false

# Performance
PARALLEL: true
